XBotInterface:
  urdf_path: $(rospack find centauro_urdf)/urdf/centauro.urdf
  srdf_path: $(rospack find centauro_srdf)/srdf/centauro.srdf
  joint_map_path: /home/embedded/xbot2_ws/src/CentauroConfig/joint_map/centauro_joint_map.yaml

ModelInterface:
  model_type: RBDL
  is_model_floating_base: true


# hal
xbotcore_device_configs:
    sim: $(rospack find centauro_config)/hal/centauro_gz.yaml
    dummy: $(rospack find centauro_config)/hal/centauro_dummy.yaml
    ec_pos: /home/embedded/xbot2_ws/src/CentauroConfig/hal/centauro_ec_all.yaml
    ec_imp: /home/embedded/xbot2_ws/src/CentauroConfig/hal/centauro_ec_all.yaml
    ec_ub_imp: /home/embedded/xbot2_ws/src/CentauroConfig/hal/centauro_ec_all.yaml
    ec_idle: /home/embedded/xbot2_ws/src/CentauroConfig/hal/centauro_ec_all.yaml


# threads
xbotcore_threads:
    rt_main:  {sched: fifo , prio: 60, period: 0.002, core_id: 2}
    nrt_main: {sched: other, prio: 0 , period: 0.005, core_id: 3}


# plugins
.ctrl_override: &ctrl_override
    type: map<int>
    value:
        j_wheel_1: 2
        j_wheel_2: 2
        j_wheel_3: 2
        j_wheel_4: 2
        dagana_2_claw_joint: 0

xbotcore_plugins:

    homing:
        thread: rt_main
        type: homing
        params:
          ctrl_override: *ctrl_override

    ros_io: {thread: nrt_main, type: ros_io}

    ros_control: 
        thread: nrt_main
        type: ros_control
        params:
          ctrl_override: *ctrl_override

    omnisteering:
        type: omnisteering_controller_plugin
        thread: nrt_main 
        params:
          wheel_names: 
            value: [wheel_1, wheel_2, wheel_3, wheel_4]
            type: vector<string>
          wheel_radius: 
            value: [0.124, 0.124, 0.124, 0.124]
            type: vector<double>
          max_steering_speed:
            value: 3.0
            type: double

    impedance_control:
      type: controllermanager
      thread: rt_main
      params:
        stack_path: /home/embedded/riccardo_ws/src/riccardo_giacchino_master_thesis/CentauroConfig/stack_problem.yaml
        stab_controller_path: /home/embedded/riccardo_ws/src/riccardo_giacchino_master_thesis/CentauroConfig/roll_pitch_controller_config.yaml
        stab_control_enable: 0
        
    
    ec_ros: {thread: nrt_main, type: ec_ros}

# global parameters
xbotcore_param:
  /xbot/hal/joint_safety/filter_autostart: {value: true, type: bool}
  /xbot/hal/joint_safety/filter_cutoff_hz: {value: 2.0, type: double}





